const axios = require('axios');
const captions = require('node-youtube-captions');

// Helper function to extract video ID
function getVideoId(url) {
  try {
    const pattern = /(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/;
    const match = url.match(pattern);
    if (match) {
      return match[1];
    }
    throw new Error('Could not extract video ID from URL');
  } catch (error) {
    throw new Error('Invalid YouTube URL format');
  }
}

async function getVideoInfo(videoId) {
  try {
    const response = await axios.get(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });

    const titleMatch = response.data.match(/"title":"([^"]+)"/);
    return {
      title: titleMatch ? titleMatch[1] : 'Unknown Title'
    };
  } catch (error) {
    console.error('Error getting video info:', error);
    return { title: 'Unknown Title' };
  }
}

async function getTranscript(videoId) {
  try {
    // Get video info
    const videoInfo = await getVideoInfo(videoId);
    
    // Get available caption tracks
    const tracks = await captions.getSubtitles(videoId);
    
    if (!tracks || tracks.length === 0) {
      throw new Error('No captions available for this video');
    }

    // Try to find English captions
    let track = tracks.find(t => t.lang_code === 'en');
    
    // If no English, try auto-generated English
    if (!track) {
      track = tracks.find(t => t.lang_code === 'en-US');
    }
    
    // If still no track, use the first available
    if (!track) {
      track = tracks[0];
    }

    // Get the actual transcript
    const transcript = await captions.getTranscript(track.id);
    
    if (!transcript || transcript.length === 0) {
      throw new Error('Failed to get transcript content');
    }

    // Format transcript with timestamps
    const formattedTranscript = transcript
      .map(item => `[${formatTime(item.start)}] ${item.text}`)
      .join('\n');

    return {
      ...videoInfo,
      transcript: formattedTranscript,
      language: track.lang_code,
      isAutoGenerated: track.kind === 'asr'
    };

  } catch (error) {
    console.error('Error:', error);
    throw new Error('Failed to fetch transcript: ' + error.message);
  }
}

// Helper function to format time
function formatTime(seconds) {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = Math.floor(seconds % 60);
  return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
}

module.exports = async (req, res) => {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({
      error: 'Method not allowed',
      details: 'Only POST requests are allowed'
    });
  }

  // Set CORS headers for the actual response
  res.setHeader('Access-Control-Allow-Origin', '*');

  try {
    const { url } = req.body;
    
    if (!url || typeof url !== 'string') {
      return res.status(400).json({
        error: 'Invalid request',
        details: 'URL is required and must be a string'
      });
    }

    const videoId = getVideoId(url);
    
    try {
      const result = await getTranscript(videoId);
      return res.json(result);
    } catch (error) {
      console.error('Transcript Error:', error);
      return res.status(400).json({
        error: 'Failed to get transcript',
        details: error.message
      });
    }
  } catch (error) {
    console.error('Error:', error);
    return res.status(400).json({
      error: 'Failed to process request',
      details: error.message
    });
  }
};
